// Package router generates Traefik file-provider dynamic config from the set
// of live ingress routes. It is the ONLY package that knows Traefik's config
// shape; it imports neither pgx nor the Docker SDK, taking plain Route values
// so the control plane stays Docker-free while still steering traffic.
package router

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Route struct {
	Key              string // stable per-environment id (env8)
	Hostname         string
	ServiceContainer string // cc-{env8}-r{rev}-{slot}-{ingress}
	Port             int
}

type Router struct{ dir string }

func New(dir string) *Router { return &Router{dir: dir} }

// Sync writes the whole dynamic config from the current routes, atomically
// (temp file + rename) so Traefik's watcher never reads a half-written file.
// Regenerating the full file each call means a removed route simply disappears.
func (r *Router) Sync(routes []Route) error {
	if err := os.MkdirAll(r.dir, 0o755); err != nil {
		return err
	}
	sort.Slice(routes, func(i, j int) bool { return routes[i].Key < routes[j].Key })

	var b strings.Builder
	b.WriteString("# generated by composectl — do not edit\nhttp:\n  routers:\n")
	for _, rt := range routes {
		fmt.Fprintf(&b, "    r-%s:\n      rule: \"Host(`%s`)\"\n      entryPoints: [\"web\"]\n      service: s-%s\n",
			rt.Key, rt.Hostname, rt.Key)
	}
	b.WriteString("  services:\n")
	for _, rt := range routes {
		fmt.Fprintf(&b, "    s-%s:\n      loadBalancer:\n        servers:\n          - url: \"http://%s:%d\"\n",
			rt.Key, rt.ServiceContainer, rt.Port)
	}

	tmp := filepath.Join(r.dir, ".composectl.yml.tmp")
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, filepath.Join(r.dir, "composectl.yml"))
}
